#!/bin/bash

#The script is developed for Debian 11 (Apache2 + MariaDB 10.0.3 + PHP 7.4 + Wordpress on Debian 11) 
#User running the script must be included in sudo group.
#If there SUDO is not installed, execute next command
#apt install sudo
#While executing mysql_secure_installation you don't need to set up root password, cause it will be generated by openssl randomizer in next steps

echo ============== LAMP installation ==============
#Updating repository software lists
sudo apt update -y

echo ============== Apache2 installation ==============

sudo apt install apache2 -y
echo Done.

echo - Configuring Apache2...
#Setting apache2 in autorun and start service
echo - Adding Apache2 in autorun
sudo systemctl enable apache2
echo - Starting Apache2...
sudo systemctl start apache2
echo Done.

echo - Activating Apache Rewrite module
sudo a2enmod rewrite
sudo systemctl restart apache2
echo Apache2 installed.

echo ============== MariaDB installation ==============

#Seting up variables
MARIADB_USER=wordpress
MARIADB_DB_NAME=wordpress
MARIADB_DB_HOST=localhost

sudo apt install mariadb-server mariadb-client -y
echo - Configure MariaDB serure settings...
sudo mysql_secure_installation

echo - Adding MariaDB in autorun
sudo systemctl enable mariadb
echo - Starting MariaDB..
sudo systemctl start mariadb 

# Generate random passwords for 'root' and 'wordpress' accounts
echo Generating MariaDB passwords
MARIADB_ROOT_PWD=$(openssl rand -base64 9)
MARIADB_WORD_PWD=$(openssl rand -base64 9)

echo Creating MariaDB initialization script... 
cat > /tmp/mariadb_init.sql <<EOF
ALTER USER 'root'@'$MARIADB_DB_HOST' IDENTIFIED BY '$MARIADB_ROOT_PWD';
CREATE DATABASE $MARIADB_DB_NAME;
CREATE USER '$MARIADB_USER'@'$MARIADB_DB_HOST' IDENTIFIED BY '$MARIADB_WORD_PWD';
GRANT ALL PRIVILEGES ON $MARIADB_DB_NAME.* TO '$MARIADB_USER'@'$MARIADB_DB_HOST';
FLUSH PRIVILEGES;
EOF

# Execute and removing (after execution) the MySQL initialisation script 
echo  - Executing initialisation script
sudo mariadb < /tmp/mariadb_init.sql && rm /tmp/mariadb_init.sql

echo ============== PHP 7.4 installation ==============
sudo apt install php7.4 php7.4-mysql libapache2-mod-php7.4 php7.4-cli php7.4-cgi php7.4-gd -y

#Seting up variables
PHP_PATH=/var/www/html

#Creating info file
sudo cat > $PHP_PATH/info.php <<EOF 
<?php
phpinfo();
?>
EOF

echo ============== WordPress installation ==============
echo - Installing WordPress...

#Downloading lastest wordpress version 
wget -c http://wordpress.org/latest.tar.gz

#Expanding and unziping and removing (after execution) archive
echo - Unpacking ...
tar xzf latest.tar.gz && rm latest.tar.gz
echo Done.

#Copying wordpress data in wordpress home directory and removing unarchived data in home directory
sudo rsync -av wordpress/* /var/www/html/ && rm -r wordpress

#Create WordPress Config File
echo Configuring wp-config.php...
cat /var/www/html/wp-config-sample.php > /var/www/html/wp-config.php
sed -i "s/database_name_here/$MARIADB_DB_NAME/" /var/www/html/wp-config.php
sed -i "s/username_here/$MARIADB_USER/" /var/www/html/wp-config.php
sed -i "s/password_here/$MARIADB_WORD_PWD/" /var/www/html/wp-config.php

#Changing owner 
sudo chown -R www-data:www-data /var/www/html/

#Changing permissions
sudo chmod -R 755 /var/www/html/

#removing default index page
sudo rm /var/www/html/index.html

echo Installation finished.
echo MariaDB Accounts
echo root = $MARIADB_ROOT_PWD
echo wordpress = $MARIADB_WORD_PWD